language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang-3.9
      - cmake
      - cmake-data
      - g++-5
      - gcc-5
      - libgtest-dev
compiler:
  - clang
  - gcc
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake
install:
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  # Install a recent version of CMake
  - |
    if [[ ! -d "${DEPS_DIR}/cmake/bin" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    fi
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
  
  # Install gtest
  - cd "${DEPS_DIR}"
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz && cd googletest-release-1.8.0
  - cmake -DBUILD_SHARED_LIBS=ON . && make && sudo make install
  
before_script:
  - mkdir -p "${TRAVIS_BUILD_DIR}/build" && cd "${TRAVIS_BUILD_DIR}/build"
  - cmake -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . -- -j$JOBS
script:
  - ctest
  - make install
